export const HOME_GET_MOVIES_BEGIN = 'HOME_GET_MOVIES_BEGIN';
export const HOME_GET_MOVIES_SUCCESS = 'HOME_GET_MOVIES_SUCCESS';
export const HOME_GET_MOVIES_FAILURE = 'HOME_GET_MOVIES_FAILURE';
export const HOME_GET_MOVIES_DISMISS_ERROR = 'HOME_GET_MOVIES_DISMISS_ERROR';
